### PR TITLE
Added paperfig command (A BUG)

### PR DESCRIPTION
**Pull request by BenjaminHsieh**

### CODE REVIEW

**Comment by changsiyao** [comment]
If an existing figure in the paper directory is not in the result directory, the command is just going to skip it?

**Comment by BenjaminHsieh** [comment]
Yes

**Comment by changsiyao** [comment]
And travis fails? should we ignore?

**Comment by BenjaminHsieh** [comment]
Good to go

**Comment by changsiyao** [comment]
great！

**Comment by BenjaminHsieh** [comment]
Should probably make a note to ross that we added the paperfig command
because he already ran the make all and it will fail

**Pull request merged**
