### PR TITLE
Change path in data.py to fix travis CI fail

### PR DESCRIPTION
**Pull request by BenjaminHsieh**
Check to see if travis ci passes

### CODE REVIEW

**Comment by changsiyao** [comment]
Maybe need to import os first

**Comment by BenjaminHsieh** [comment]
do you mean in the data file?

**Comment by BenjaminHsieh** [comment]
ok finally go it to work, the coverage will decrease because the hashList is being loaded from the call to **main**, which is ignored by travis ci. Anyway, this should work for everyone, someone can merge and test it out

**Comment by BenjaminHsieh** [comment]
@brianqiu

**Comment by BenjaminHsieh** [comment]
Can also close #14

**Comment by changsiyao** [comment]
Wait, I'm having problem with this file. If I change directory to the folder above, then the path for all the files are wrong.
Traceback (most recent call last):
  File "data.py", line 42, in <module>
    check_hashes(d)
  File "data.py", line 26, in check_hashes
    digest = generate_file_md5(k)
  File "data.py", line 13, in generate_file_md5
    with open(filename, "rb") as f:
IOError: [Errno 2] No such file or directory: u'ds005/sub015/BOLD/task001_run001/QA/DVARS.png'

I got this. I think we need to change the directory back after loading the hashList, like:
if **name** == "**main**":
    os.chdir('..')
    with open('data/hashList.txt', 'r') as hl:
        d = json.load(hl)
    os.chdir('data/')
    check_hashes(d)

**Comment by BenjaminHsieh** [comment]
hmmm, weird, I have the opposite, if I add oc.chdir('data/') before check_hashes(d), then I get that same error

**Comment by changsiyao** [comment]
Other people should check, otherwise, let's ask tmr in office hours.

**Comment by BenjaminHsieh** [comment]
@changsiyao try this, I have this that works:

if **name** == "**main**":
    with open('hashList.txt', 'r') as hl:
        d = json.load(hl)
    check_hashes(d)

**Comment by BenjaminHsieh** [comment]
this assumes that you have the ds005/ in data directory

**Comment by changsiyao** [comment]
This (without all the changing directory steps) works for me, but I thought this wouldn't pass the test?

**Comment by BenjaminHsieh** [comment]
lol it passed just now

**Comment by BenjaminHsieh** [comment]
lets get someone else to check just in case and if its good we can merge it

**Comment by changsiyao** [comment]
eh...... But I suppose it's a good thing, lol~

**Comment by BenjaminHsieh** [comment]
can someone test this and merge it thanks, it will probably allow us to pass the failure in #31 @boyinggong @brianqiu @pigriver123

**Pull request merged**
