### PR TITLE
Cal t with test

### PR DESCRIPTION
**Pull request by BenjaminHsieh**
@pigriver123 @changsiyao 
I updated the calc_t.py with tests, let me know if this is something you were looking for/anything wrong

### CODE REVIEW

**Comment by changsiyao** [comment]
import numpy as np
import numpy.linalg as npl

def significant(a,b,c):
    """ 
    function to calculate t values for beta gain and beta loss for a single voxel.
    Input: a is design matrix X; b is BOLD data Y for a single voxel.

```
       c is beta values for a single voxel.

Output: t value for beta gain, t value for beta loss

Example use: significant(X, Y[:,i], beta[:,i]) 

"""
y_hat = a.dot(c)
residuals = b - y_hat
ma=npl.pinv(a.transpose().dot(a))
RSS = np.sum(residuals ** 2)
df = a.shape[0] - npl.matrix_rank(a)
MRSS = RSS / df
s2 = MRSS
v_cov = s2 * npl.inv(a.T.dot(a))
numerator1 = c[0]
denominator1 = np.sqrt(v_cov[0, 0])
t1= numerator1 / denominator1
numerator2 = c[1]
denominator2 = np.sqrt(v_cov[1, 1])
t2= numerator2 / denominator2
return t1,t2
```

Sorry, this is how I fixed it earlier, just hadn't put it up. I think the code part is the same, just need to specify that this function calculates t values for a single voxel.

**Comment by BenjaminHsieh** [comment]
ok will add those comments

**Comment by BenjaminHsieh** [comment]
the i in the example mean ith voxel right?

**Comment by BenjaminHsieh** [comment]
Please check and merge whenever possible

**Comment by changsiyao** [comment]
Yes, the i means the ith voxel.
Technically, the Y input parameter is also the BOLD data for a single voxel, but I don't know if you want to bother fixing that.

**Comment by changsiyao** [comment]
From Jiang's original pull request

**Pull request merged**
