### PR TITLE
update regression function and script: adding linear/quad drift

### PR DESCRIPTION
**Pull request by changsiyao**
Added linear and quadratic drift.
Haven't add smoothing function yet, will do that soon.
Just want to upload the things I have for now.

### CODE REVIEW

**Comment by BenjaminHsieh** [comment]
Ok I will update the test functions

**Comment by changsiyao** [comment]
Now, I have no idea how to merge the conflict...

**Comment by BenjaminHsieh** [comment]
0.0 commit the files in your current branch first, 
then pull the changes, you will probably get merge conflicts message, then 
You have to manually go through the each merge conflict file and follow the answer to 

http://stackoverflow.com/questions/24103490/need-help-to-understand-merge-conflict-example

then re-commit and push

**Comment by BenjaminHsieh** [comment]
lmk tomorrow if you cannot get it to work, then I will just copy and paste your code and update it

**Comment by changsiyao** [comment]
OK, fixed merge conflicts. :D

**Comment by BenjaminHsieh** [comment]
ok good, someone else can give this a check?

**Comment by briankleinqiu** [comment]
Not all the input/output is updated to include the drifts but doesn't really matter, it looks good, thanks for the work you guys

**Pull request merged**
