### PR TITLE
fix an order issue in code/scripts, minor edits

### PR DESCRIPTION
**Pull request by briankleinqiu**
So graph_lin_diagnostics is saving res_fitted_log and res_fitted to the paper/figures directory and not the results/figures directory. 

We want to fix that right?

Also, the graph looks a little weird to me now. 

res_fitted

### CODE REVIEW

**Comment by changsiyao** [comment]
We can fix it if you want to, it's not necessary, since we are just generating this one plot that's included in the paper.
Also, in code/Makefile,     make diagnostics needs to be before make glm, like you said, can you fix that as well.

**Comment by briankleinqiu** [comment]
Ok, not worried about the path too much really. It's more that the plot looks strange to me, does it look weird to you? When you run make diagnostics that's the plot that'll get pushed to the paper/figure so that's the one that could end up in our paper

**Comment by changsiyao** [comment]
@BenjaminHsieh Were you getting this plot when you plotted a while ago?

**Comment by BenjaminHsieh** [comment]
no, i had something different I think this may be a floating int problem that matthew was talking about

**Comment by BenjaminHsieh** [comment]
when loading in the BOLD image/getting the data, try the astype(float), something like this:

`img = nib.load("our data nii")
data = img.get_data().astype(float)
[do other work]
`
@changsiyao

**Comment by BenjaminHsieh** [comment]
@brianqiu

**Comment by changsiyao** [comment]
So we have to go in and change all the scripts with that?

**Comment by BenjaminHsieh** [comment]
ummm probably...lol, see if this fixes the res vs actual first

**Comment by BenjaminHsieh** [comment]
yeah i think just change it for the res vs actual plot, b/c we dont have time to run the other things again and the results look ok

**Comment by changsiyao** [comment]
In script/neural_behavial_plot.py, line 17, "from neural_behavior import plot_neur_beh" needs to be changed to "from plot_neural_behavior import plot_neur_beh", @brianqiu can you change it with this pull request?

**Comment by briankleinqiu** [comment]
will do in a bit. laptop is crapping out on me right now as im running make glmstandard

**Comment by briankleinqiu** [comment]
nice fix ben, that worked. can prbly merge in now. 
res_fitted

**Pull request merged**
