### PR TITLE
Slides parts 04 and 06

### PR DESCRIPTION
**Pull request by BenjaminHsieh**
Model selection graphs and future work slide:

Note: have to merge #97 before this one so that the correct res_fitted graph shows up
Note 2: I was not sure what other future works you guys have in mind, feel free to add to slide 06 or let me know

### CODE REVIEW

**Comment by BenjaminHsieh** [comment]
is this ok?

**Comment by pigriver123** [comment]
Thanks for the work.It looks pretty nice.

**Comment by boyinggong** [comment]
You mistakenly put the wrong fitted vs residual figure in the slide. Please check it.

**Comment by changsiyao** [comment]
Didn't he change the graph to the correct one?

**Comment by boyinggong** [comment]
I don't think so.

**Comment by changsiyao** [comment]
I see that he's using the one that shows residuals with mean 0 and constant variance.

**Pull request merged**
