### PR TITLE
organize, rename, create new directories

### PR DESCRIPTION
**Pull request by BenjaminHsieh**
Reorganized code directory and modified all paths in functions and scripts. Also fixed a bug in regression script. 

Please let me know if this it the organization you guys had in mind. 
RN I have: 
code/ - utils/      - tests/
                         - {functions.py} 
         - scripts/  - {scripts.py}

### CODE REVIEW

**Comment by BenjaminHsieh** [comment]
Ok the organization wasn't clear, but something like this:
.
├── Makefile
├── scripts
│   ├── findoutlier.py
│   ├── graphoutlier.py
│   ├── #regression_script.py#
│   └── regression_script.py
├── temp.txt
└── utils
    ├── behavtask_tr.py
    ├── behavtask_tr.pyc
    ├── graphoutlier_functions.py
    ├── graphoutlier_functions.pyc
    ├── **init**.py
    ├── **init**.pyc
    ├── outlierfunction.py
    ├── outlierfunction.pyc
    ├── pearson.py
    ├── pearson.pyc
    ├── regression_functions.py
    ├── regression_functions.pyc
    ├── stimuli.py
    └── tests
        ├── **init**.py
        ├── **init**.pyc
        ├── test_graph_functions.pyc
        ├── test_graphoutlier_functions.py
        ├── test_graphoutlier_functions.pyc
        ├── test_outlierfunction.pyc
        ├── test_pearson_1d.py
        ├── test_pearson_1d.pyc
        ├── test_pearson_2d.py
        ├── test_pearson_2d.pyc
        └── test_regression_functions.pyc

**Comment by changsiyao** [comment]
Looks good.
Except that I just edit the regression files too. I feel like there might be merge conflict now, need to figure that out...

**Comment by BenjaminHsieh** [comment]
yeah we might want to merge one of the pull requests asap to avoid further merge conflicts, preferably this one?

**Comment by changsiyao** [comment]
Probably. You only moved the files around and didn't do any actual code changes, right?
Then, I'm just gonna go ahead and merge this. OK?

**Comment by BenjaminHsieh** [comment]
I changed paths and fixed a bug in regression_script: changes hrt_ to hrf_ in line 73, but yeah should be ok and easy to manually check though

**Pull request merged**
