### PR TITLE
new things guys

### PR DESCRIPTION
**Pull request by pigriver123**
edit Makefile in data
edit  python code in code

### CODE REVIEW

**Comment by BenjaminHsieh** [comment]
wow a lot of code! I think we should also think of some nosetests for the function before we merge, for example the directory the code is currently pointing to may not exist in our computers

**Comment by changsiyao** [comment]
In the data.py file, it still says the example file and hash. I think I can fix that.

**Comment by changsiyao** [comment]
unzip part also needs revision, don't change directory. I think giving the path directly in the unzip line is a better idea. Like: gunzip ds005/sub00${i}/BOLD/task001_run00${j}/bold.nii.gz

**Comment by briankleinqiu** [comment]
So, we should close this pull request and not merge it? Siyao's pull request is the most recent version of this right?

**Comment by changsiyao** [comment]
The python code in the code folder is still useful, I think. But not other files.

**Comment by briankleinqiu** [comment]
Ok, not completely sure how to handle that. How about we close this and make new pull request with just that then

**Pull request closed without merging**
