### PR TITLE
New pull request for Makefile and graph codes

### PR DESCRIPTION
**Pull request by changsiyao**
Boying made a pull request for the updated data.py file

### CODE REVIEW

**Comment by changsiyao** [comment]
Boying forgot to change the directory path when generating the hashlist, so I updated it here. But since we need to read all the hash from this txt file when checking them, the test keeps on failing because it can't find the file...

**Comment by briankleinqiu** [comment]
I assume by test we mean the data.py file? When we run that what's the output?

Is there any reason # print("The file {0} has the correct hash.".format(k)) is commented out?

is it possible we need to define the path name for hashList.txt in the json.load in data.py?

If that doesn't work, what if we just combine generatehash.py and data.py?

**Comment by changsiyao** [comment]
We edited the data.py file, so that right now, it checks every single file in the unzipped data ds005 folder. The script should return whether all the hash are correct or not. I commented out the print correct hash line because there are 1231 files in total and I didn't want to print the line 1231 times... we can easily uncomment it if you guys think necessary.
The reason we uploaded a txt file that includes all the hash is that we are not regenerating the hash every time; we are just comparing our hashes to the hashes in the txt file. (So, the generatehash.py is not for everybody to run; we just put it there, just in case you guys want to see it.)
Finally, I'm not sure what the path name for the txt file would be. On my own computer, ds005 folder and these scripts are all in the data folder, so I didn't have to specify the path...

**Comment by briankleinqiu** [comment]
Ah, gotcha. So the problem is for sure that the data.py file can't find hashList.txt?

I see hashList.txt is put in the data folder as well. Since data.py is executed from the same folder it shouldn't be an error of finding it, but maybe try and use the absolute path temporarily and see if that fixes the problem

**Comment by changsiyao** [comment]
Now, the reading txt line seems to be working, but the next line that checks the hash tag is still failing...

**Comment by changsiyao** [comment]
Sorry for spaming you guys with pull requests, just trying to figure out what's failing.

**Comment by briankleinqiu** [comment]
No problem!

What's the output? How many hashes right are we getting? From what I checked the generate_file_m5 is producing the correct hashes that we're getting in hashLib.txt

Fyi, probably don't need to make a pull request for each test?

**Comment by changsiyao** [comment]
I don't know what's wrong... It seems that the check_hashes function in the main function has problems, but that part was working fine before I started testing for every single file...

**Comment by briankleinqiu** [comment]
Is the makefile generating data in the exact same structure, for example ds005/sub015/BOLD/task001_run001/QA/DVARS.png?

**Comment by briankleinqiu** [comment]
Also, in the hashLib.txt files the BOLD data is in nii.gz

Is the makefile's generated data also in nii.gz?

**Comment by changsiyao** [comment]
I just change it back to the original code they gave us to try the test, it still fails with the check_hashes(d) part... I remember it working fine a couple days ago... I don't know what's going on... Maybe we should just ask tmr in class.

**Comment by briankleinqiu** [comment]
Here's an error I found:

the hashList.txt file has a key called 'ds005/sub001/BOLD/task001_run001/QA/fd_sub1run1.png'

But this file doesn't exist in my ds005!

Can we look into how that was generated?

**Comment by changsiyao** [comment]
My hash list was not accurate, cuz I forgot I did some changes in the folder. The new hash list should be correct.
sorry about that.
There should be 1087 files in the folder in total.
But the test still failed... I think we should just ask tmr...

**Comment by briankleinqiu** [comment]
Ok this hashList works and tells me 1087 correct files. Whats the output on your end

**Comment by changsiyao** [comment]
Or can somebody download the new hash txt file and run the data.py file on their own computer to see what happens?

**Comment by changsiyao** [comment]
I got 1087 files too, so it sounds fine. Idk why the test keeps failing.

**Comment by briankleinqiu** [comment]
I'm trying the makefile now. Will take a few minutes to load the data

**Comment by briankleinqiu** [comment]
OK got it to work and the issue is probably what I commented before, that the unzipping might be messing things up. In the makefile if you delete all of the unzipping stuff and just keep the data and validate part, it should work.

Also it gave me an error with the textfile data/hashList.txt, so I deleted the data/ path and it worked. Weird!

**Comment by changsiyao** [comment]
Am I still missing anything...?

**Comment by changsiyao** [comment]
How do you check the Makefile on your own computer?

**Comment by briankleinqiu** [comment]
Hmmm maybe change "data/hashList.txt" to just "hashList.txt"?

If that gets us nowhere I give up and lets look at it tomorrow.

Dang, I copied and pasted the files into my local repository and tested them there but I already deleted it

**Comment by changsiyao** [comment]
It seems that the path data/ has to be added... But Idk what's wrong. We'll just ask tmr.

**Pull request merged**
