### PR TITLE
Main readme and make update

### PR DESCRIPTION
**Pull request by BenjaminHsieh**

### CODE REVIEW

**Comment by BenjaminHsieh** [comment]
@changsiyao @pigriver123 can you guys double check the plot_neural_behavior.py fix

**Comment by changsiyao** [comment]
yes, Y should just be neural, this should be right now.

**Comment by BenjaminHsieh** [comment]
Ok merge when travis is done

**Comment by briankleinqiu** [comment]
Travis still hasn't compiled? Is this the error matthew put up on piazza today

**Comment by BenjaminHsieh** [comment]
lol probably

**Pull request merged**
