### PR TITLE
Some more confusion fun

### PR DESCRIPTION
**Pull request by BenjaminHsieh**
@boyinggong, I was playing around with some confusion matrix stuff too this afternoon, you think we can combine this code? 
The functions just creates confusion matrix, gets probability threshold with lowest # of wrong predictions, and plots prop of wrong predictions vs prob thresholds

Also when saving the figures (both ROC and confusion plots), can we plot all 16 plots into 1 figure using subplots?
#110

### CODE REVIEW

**Comment by boyinggong** [comment]
I think they are pretty much the same? It's just that I put them all in one function? And I didn't calculate the probability threshold, but calculated the area of the curve. I will try to combine the plots.

**Comment by BenjaminHsieh** [comment]
ok, just copy and paste whatever in this pull request that makes the scripts/functions cleaner and better documented

**Comment by BenjaminHsieh** [comment]
@boyinggong , let me know if you want me to combine this pull request and #110

**Comment by boyinggong** [comment]
I'm doing this.

**Comment by BenjaminHsieh** [comment]
closing, see #110

**Pull request closed without merging**
