### PR TITLE
Slides update

### PR DESCRIPTION
**Pull request by BenjaminHsieh**
CI skip @brianqiu  I just included the old fig back for completeness, the make is good

### CODE REVIEW

**Comment by BenjaminHsieh** [comment]
This is good, someone merge and close #151

**Comment by changsiyao** [comment]
merge conflict?

**Comment by BenjaminHsieh** [comment]
yeah let me fixed it, because #151 was merged before this

**Comment by BenjaminHsieh** [comment]
ok good to go

**Pull request merged**
