### PR TITLE
updated the correct file name and hash

### PR DESCRIPTION
**Pull request by changsiyao**
file name and hash was still the example, changed it to our data.

### CODE REVIEW

**Comment by changsiyao** [comment]
Also fixed Jiang's code for unzipping

**Comment by briankleinqiu** [comment]
Both commits look good to me

**Comment by BenjaminHsieh** [comment]
talked to ross about hash for data, we should make hash for the unzipped folder instead

**Comment by briankleinqiu** [comment]
also separate the graphing code in a different file than the summary statistics code if possible

and adding some comments and docstring would be useful

**Comment by changsiyao** [comment]
What do you mean by separate the graphing code in a different file than the summary statistics code? I only have the graphing code in that file. Jiang has the summary statistics code.

**Comment by changsiyao** [comment]
Also, how do you make hash for the unzipped folder which is a directory, not a file.

**Comment by changsiyao** [comment]
eh... accidentally merged... what should I do...

**Comment by BenjaminHsieh** [comment]
Revert the new pull request I made

**Comment by BenjaminHsieh** [comment]
Also, for the hashing of directory, check this answer, might help: 
http://unix.stackexchange.com/questions/35832/how-do-i-get-the-md5-sum-of-a-directorys-contents-as-one-sum

**Comment by changsiyao** [comment]
Actually, is there a way to remerge these files. I think we need to make changes to these files by tonight, so let's just use the tgz hash first.

**Comment by BenjaminHsieh** [comment]
i not sure how, easier to submit a new pull request i think

**Comment by changsiyao** [comment]
I can't, cuz it says there's no new changes.

**Pull request merged**
