### PR TITLE
Mergecond

### PR DESCRIPTION
**Pull request by BenjaminHsieh**
Check if this works, merging all tasks

### CODE REVIEW

**Comment by changsiyao** [comment]
I'm getting an error like "append() takes at most 3 arguments (4 given)" when calling merge_cond()... Can you check that?

**Comment by BenjaminHsieh** [comment]
Yeah will check

**Comment by BenjaminHsieh** [comment]
Should work now

**Comment by changsiyao** [comment]
behav_task.shape[1] != 12 not 9, I think.
time_course = np.zeros((n_trs, 10))

**Comment by BenjaminHsieh** [comment]
Sry got sloppy

**Comment by BenjaminHsieh** [comment]
Someone can merge this if we are good

**Pull request merged**
