### PR TITLE
Test for regression, outliers

### PR DESCRIPTION
**Pull request by BenjaminHsieh**
Please do a check of this, when running the regression test, have to run from project-theta directory and use 'make test'
The nosetest fails if I run it from 'code/test' directory, something weird with setting the path, still have to look into it

### CODE REVIEW

**Comment by BenjaminHsieh** [comment]
Finally this passed the travis, imma cry...
anyway,
Added 3 test condition files to the test directory, Jarrod said this was ok
Please give this a check: the test_regression script needs to be run from main directory or code directory by "make test"

Also I dont know how much the regression functions have changed so these test are based on the old version (current dev version) @changsiyao

**Comment by BenjaminHsieh** [comment]
Dont merge yet, need to wait for #70

**Comment by BenjaminHsieh** [comment]
Added functions for qqplot and res_fitted, updated tests for quad and linear drift

**Comment by briankleinqiu** [comment]
Looks awesome. The plots look really useful

**Pull request merged**
